apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-api-deployment-test
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: api-test
        image: yoursureshdockerhub/jenkins-eks-be-testing:latest
        ports:
        - containerPort: 8080
        env:
        - name: MODE
          value: "production"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-service:5432/postgres"
