apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-webapp-deployment-test
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp-test
        image: yoursureshdockerhub/jenkins-eks-fe-testing:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://ab0a6c0e3207e49f489afad48c98a069-1659234077.eu-central-1.elb.amazonaws.com:8080/api"
        

   
        
